### ISSUE TITLE
テキストや画像ホバーをmixin化して共通化

### ISSUE THREAD

**Issue by jungissei** [jungissei/jquery.jungissei.com#35]
下記のような感じで。
画像ありバージョンもほしい。テキストにaタグが付与されていて、サムネもホバーアニメーションされるように。group-hoverが良いかな。

```scss
@mixin site_common_txt_hover1 {
  color: $color_main1;
  transform: color 0.2s;

  @include hover{
    color: $color_main1_hover;
  }
}

```
