### ISSUE TITLE
【SCSS】テキスト関連

### ISSUE THREAD

**Issue by jungissei** [jungissei/jquery.jungissei.com#75]
```scss
// --------------------------------------
// テキスト共通スタイル
// --------------------------------------
.site_common_text1{
・・・
}


// --------------------------------------
// テキスト装飾
// --------------------------------------
$text-bold-styles: (
  'medium': 500,
  'default': 400
);

@each $style, $weight in $text-bold-styles {
  .text-bold-#{$style} {
    font-weight: $weight;
  }
}


// --------------------------------------
// テキストの配置
// --------------------------------------
$text-alignments: (
  'center': center,
  'left': left,
  'right': right
);

@each $alignment, $value in $text-alignments {
  .text-#{$alignment},
  .text-#{$screen_type}-#{$alignment} {
    text-align: $value;
  }
}
```
