### ISSUE TITLE
タブ表示切替アニメーション safari 動いてない

### ISSUE THREAD

**Issue by jungissei** [jungissei/jquery.jungissei.com#84]
animationで動く
```scss
@keyframes tab_hide {
  from {
    opacity: 1;
  }

  to {
    opacity: 0;
    display: none;
  }
}

@keyframes tab_show {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

```
